services:
  outer-proxy:
    container_name: "outer-proxy"
    build:
      context: "."
      dockerfile: Dockerfile
    extra_hosts:
      - "outer-proxy.homelab.dev:10.20.30.2"
      - "inner-proxy.homelab.dev:10.20.30.3"
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./outer-proxy/conf:/etc/nginx
      - ./outer-proxy/logs:/var/log/nginx
    networks:
      fakelan:
        ipv4_address: 10.20.30.2

  inner-proxy:
    container_name: "inner-proxy"
    build:
      context: "."
      dockerfile: Dockerfile
    extra_hosts:
      - "outer-proxy.homelab.dev:10.20.30.2"
      - "inner-proxy.homelab.dev:10.20.30.3"
    ports:
      - "9090:80"
      - "9443:443"
    volumes:
      - ./inner-proxy/conf:/etc/nginx
      - ./inner-proxy/logs:/var/log/nginx
    networks:
      fakelan:
        ipv4_address: 10.20.30.3

  backend:
    container_name: "backend"
    build:
      context: "./backend"
    ports:
      - "4444:4444"
    networks:
      fakelan:
        ipv4_address: 10.20.30.4

networks:
  fakelan:
    ipam:
      config:
        - subnet: "10.20.30.0/24"
